Test with multiple Python versions (#80)
Run CI tests with Python 3.8 and Python 3.9 and publish constraints file in CI artifacts (for now).

Python 3.7 is not included because of the following error:

```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/circleci/project
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```